- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: dotfiles, tags: "dotfiles" }
    - { role: brew, tags: "brew" }
    - { role: zsh-git-prompt, tags: "zsh-git-prompt" }
    - { role: dropbox, tags: "dropbox" }
