- name: Create symlink
  file: src={{ item }} dest=~/.{{ item | basename}} state=link
  with_fileglob:
    - zprofile
    - zshrc
    - zsh_aliases
    - tmux.conf
    - gitconfig
    - gitignore_global
    - gemrc
