- name: Update Homebrew
  homebrew: update_homebrew=yes upgrade_all=yes
- name: Tap Homebrew Cask
  command: brew tap caskroom/cask
- name: Install formula
  homebrew: name={{ item }}
  with_items:
    - autojump
    - brew-cask
    - git
    - hub
    - imagemagick
    - openssl
    - rbenv
    - readline
    - reattach-to-user-namespace
    - ruby-build
    - tmux
    - tree
    - wget
    - zsh
    - zsh-completions
- name: Change default shell
  command: chsh -s /bin/zsh
  sudo: yes
- name: Install App
  homebrew_cask: name={{ item }}
  with_items:
    - atom
    - butter
    - google-chrome
    - google-japanese-ime
    - growl-fork
    - iterm2
    - karabiner
    - kensington-trackball-works
    - libreoffice
    - moom
    - vagrant
    - virtualbox
    - yorufukurou
    # - dropbox osx10.10 では cask で上手くインストールできなかった
