- name: Update Homebrew
  homebrew: update_homebrew=yes upgrade_all=yes
- name: Install formula
  homebrew:
    name:
      - ghq
      - git
      - hub
      - imagemagick
      - openssl
      - peco
      - rbenv
      - readline
      - reattach-to-user-namespace
      - ruby-build
      - tmux
      - tree
      - wget
      - zsh
      - zsh-completions
- name: Change default shell
  command: chsh -s /bin/zsh
  become: yes
- name: Install App
  homebrew_cask:
    name:
      - google-chrome
  ignore_errors: result.msg.startswith('Error: It seems there is already an App at')
