- name: Clone dotfiles
  git: repo=https://github.com/flada-auxv/dotfiles.git
       dest=~/.dotfiles
- name: Create symlink
  file: src=~/.dotfiles/{{ item }} dest=~/.{{ item }} state=link
  with_items:
    - zprofile
    - zshrc
    - zsh_aliases
    - tmux.conf
    - gitconfig
    - gitignore_global
    - gemrc
